# Generated by Django 5.2 on 2025-04-29 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('hero_image', models.URLField()),
                ('project_type', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('tools', models.JSONField()),
                ('role', models.JSONField()),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('images', models.JSONField()),
                ('results', models.TextField()),
                ('project_link', models.URLField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('projects_completed', models.PositiveIntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
